name: CI

on:
  push:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: check wget
        run: |
          $WebClient = New-Object System.Net.WebClient
          $WebClient.DownloadFile("https://adn.harmanpro.com/softwares/wares/1846_1596143552/NetLinxStudioSetup_4_4_1914.zip","NetLinxStudioSetup.zip")
          ls
          
      - name: unzip folder
        run: |
          7z x NetLinxStudioSetup.zip
          ls

