name: CI

on:
  push:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-2019

    steps:
      # - uses: actions/checkout@v3

      - name: wget files
        run: |
          $WebClient = New-Object System.Net.WebClient
          $WebClient2 = New-Object System.Net.WebClient
          $WebClient.DownloadFile("https://adn.harmanpro.com/softwares/wares/1846_1596143552/NetLinxStudioSetup_4_4_1914.zip","NetLinxStudioSetup.zip")
          $WebClient2.DownloadFile("https://drive.google.com/uc?export=download&id=1pqBc7BlU-QQ9nTTXRBd5MjZPJCUp7iz3&confirm=t","AMXShare.zip")
          ls
          
      - name: unzip folder
        run: |
          7z x NetLinxStudioSetup.zip
          7z x AMXShare.zip
          cd AMXShare
          ls
          cd COM
          nlrc.exe
