name: CI

on:
  push:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      #- name: wget files
      #  run: |
      #    $WebClient = New-Object System.Net.WebClient
      #    $WebClient2 = New-Object System.Net.WebClient
      #    $WebClient.DownloadFile("https://adn.harmanpro.com/softwares/wares/1846_1596143552/NetLinxStudioSetup_4_4_1914.zip","NetLinxStudioSetup.zip")
      #    $WebClient2.DownloadFile("https://drive.google.com/uc?export=download&id=1pqBc7BlU-QQ9nTTXRBd5MjZPJCUp7iz3&confirm=t","AMXShare.zip")
      #    ls
          
      - name: compile folder
        run: |
          ls
          cd "C:\Program Files (x86)\Common Files\AMXShare\COM"
          NLRC.exe "D:\a\test_CI\test_CI\Source\Main.axs" "-ID:\a\test_CI\test_CI\Include" "-MD:\a\test_CI\test_CI\Module" "-xD:\a\test_CI\test_CI\Compiled"
          ls D:\a\test_CI\test_CI\Source\
